### ISSUE TITLE
Verify Cores data.json and Required Assets

### ISSUE THREAD

**Issue by hallem** [hallem/pupdate#13]
It seems some of the cores are missing the required: true setting on some of the specified assets (bios, rom, etc.). For example, the spiritualized1997 Super GameBoy core.

Check to see how systemic this issue is with the other cores. Yeah it's a long ass list.

**Comment by mattpannella** [comment]
yeah this has been a pain in the ass. the vast majority of the spiritualized cores don't actually set their required assets to required

**Comment by hallem** [comment]
@mattpannella I saw that. Super annoying, but relatively easy to "fix" if we want to.

One way to do it, without needing a JSON change, would be to check the archive for the file and if it's there download it, otherwise skip it.

**Comment by hallem** [comment]
never mind, looks like this already does that. not sure why I wasn't seeing it happen before. :shrug:
