### ISSUE TITLE
Redesign the Menu system

### ISSUE THREAD

**Issue by hallem** [hallem/pupdate#2]
- move lesser used menu items to a submenu
- see what can be done with the core selection menu systems
- see what can be done to bring the settings menu into a standard submenu
- see what can be done to bring the image packs menu into a standard submenu

**Comment by hallem** [comment]
Menu Structure

```
0. Update All
1. Update Firmware
2. Select Cores
   -- Should this kick into installing the new cores that are selected right away?
   -- Should this be built into the menu system or dynamically generated like it is?
3. Download Assets
4. Backup Saves
5. Pocket Setup
   a. Download Platform Image Packs
   b. Download Pocket Library Images -- NEW FEATURE
      -- only supported platforms GB, GBC, GG, maybe others when you can verify with someone who has the new adapters
      i.   Spiritualized1997
           -- Dropbox link
           -- Should be moved to github or the archive maybe?
           -- Looks like it's in the archive already
      ii.  CodeWario / libretro-thumbnails - Box Arts
      iii. CodeWario / libretro-thumbnails - Snaps
      iv.  CodeWario / libretro-thumbnails - Titles
      v.   Go Back
   c. Download GameBoy Palettes -- NEW FEATURE (Discord & github)
   d. Generate Instance JSON Files (PC Engine CD)
   e. Generate Game & Watch ROMs
   f. Enable All Display Modes
   g. Go Back
6. Pocket Maintenance -- NEW FEATURE
   a. Reinstall Cores
   b. Uninstall Cores
      - Prompt: Do you want to delete the ROMs for the core?
      - Prompt: Do you want to delete the Saves for the core?
   c. Uninstall Pocket Extras
      -- provide a list of the installed extras like the uninstall feature
      -- uninstall the core with prompts
      -- reinstall the base core & download the assets if necessary
   d. Go Back
7. Pocket Extras -- NEW FEATURE
   a. Download extras for Eric Lewis's Donkey Kong
   b. Download extras for Eric Lewis's Radar Scope -- this includes the DK roms too, what to do?
   c. Download extras for Jotego's Bubble Bobble (jtbubl) (beta)
   d. Download extras for Jotego's Capcom CPS 1 (jtcps1)
   e. Download extras for Jotego's Capcom CPS 1.5 (jtcps15)
   f. Download extras for Jotego's Capcom CPS 2 (jtcps2)
   g. Download extras for Jotego's Pang / Super Pang (jtpang)
   h. Toaplan 2 Single Platform Arcade Multi -- Not sure how to handle this one yet.
   i. Download all extras
   k. Go Back
8. Settings
9. Exit
```

-- Where to put the Super GameBoy enhancements? (SGB2, 8x7) Maybe Pocket Extras?
   Talk to dyreschlock about adding them to his repo.

-- SGB Assets don't auto download because of being marked as required false.
   Something to check and see what can be done about in an automated way with pupdate.
   Maybe something else to be included in Pocket Extras?

**Comment by mattpannella** [comment]
when i have more time to really look this over i'll try and give more feedback, but one thing that just stood out is the Pocket Extras section. i'm hesitant to add a bunch of custom/hardcoded stuff in here that depends on someone else's repo 
could we come up with some kind of config/json/whatever format that people can host on their own repos that is basically a defined menu structure.
so the pocket extras repo can have `pupdatemenu.json` which contains whatever list of items he wants downloadable, with paths to each one. this way we can just dynamically build the menu at runtime based on thaht file (and then we can just add support for any number of extra repos)

**Comment by hallem** [comment]
@mattpannella Yeah that makes sense. I was only looking at it feature wise since it seemed a decent amount of people used both and without a little love, the two don't really work well together.

For everything except the Toaplan 2 changes, the [code](https://github.com/hallem/pupdate/blob/pocket-extras/src/partials/Program.PocketExtras.cs) is really straight forward at least. Even integrating it into the core update process so it doesn't get overwritten (which really only applies to the data.json changes).

I like the dynamic menu idea. The JSON file would have to contain a list of instructions so we knew exactly what to download and what to replace/update for the core. I'm not sure off the top of my head how it would be integrated with the updater though, so it wouldn't get effectively overwritten when a new core update happens.

If you don't want to be linked to or depend on other repos, the other feature I was considering doing was the alternative library images from libretro-thumbnails / CodeWario. Nothing earth shattering, just making it easy to change things up like for the platform images.

Here's what the menu would look like without that stuff so you have a cleaner visual:
````
0. Update All
1. Update Firmware
2. Select Cores
   -- Should this kick into installing the new cores that are selected right away?
   -- Should this be built into the menu system or dynamically generated like it is?
3. Download Assets
4. Backup Saves
5. Pocket Setup
   a. Download Platform Image Packs
   b. Download Pocket Library Images -- NEW FEATURE
   c. Download GameBoy Palettes -- NEW FEATURE (Discord & github)
   d. Generate Instance JSON Files (PC Engine CD)
   e. Generate Game & Watch ROMs
   f. Enable All Display Modes
   g. Go Back
6. Pocket Maintenance -- NEW FEATURE
   a. Reinstall Cores
   b. Uninstall Cores
      - Prompt: Do you want to delete the ROMs for the core?
      - Prompt: Do you want to delete the Saves for the core?
   d. Go Back
8. Settings
9. Exit
````

I should have a prototype ready soon-ish, I was playing with this menu layout today.

**Comment by mattpannella** [comment]
re: updater all overwriting extras
would could basically maintain a list of installed "extras" (generate some kind of key, like repo name + item name or something) and re-apply them after each full update all call?

and i think maybe the extras feature could be as simple as a repo hosts a file that contains a title, link to a dir or package on the repo, and then a path where to extract it on the sd card?
i dont know. i'd need to think about this more cuz i'm sure there would be some issues i'm not thinking of now. i'm sick and half out of it lol

also also, i thikn that basic menu structure looks great

**Comment by hallem** [comment]
> re: updater all overwriting extras
would could basically maintain a list of installed "extras" (generate some kind of key, like repo name + item name or something) and re-apply them after each full update all call?

That's kinda where I was going. I added a flag to the core settings in the pupdate_settings.json that if set to true, would reapply the extra to the core after the update.

> and i think maybe the extras feature could be as simple as a repo hosts a file that contains a title, link to a dir or package on the repo, and then a path where to extract it on the sd card?

For the most part that works. I'll play with it some more. I know for one file, dyreschlock doesn't separate the cores out, but I'm sure that wouldn't be an issue for him to do.

> i dont know. i'd need to think about this more cuz i'm sure there would be some issues i'm not thinking of now. i'm sick and half out of it lol

Dude, rest up and feel better. This all can wait.

> also also, i thikn that basic menu structure looks great

Thanks. I'm almost done with the prototype. :)

**Comment by mattpannella** [comment]
i think the hardcoded pocket-extras stuff is fine for now, too. i mean, its not like there's no dependencies in the project already haha. but i like the idea of it being something where people can subscribe to whatever repos they want for stuff, if there's some kind of standardized format we can come up with 

might be a good discussion to have on the openfpga inventory repo? cuz maybe we can set up a new endpoint there to list available "extras" repos. plus i think neil might some thoughts for integrating this stuff with pocket sync too

**Comment by hallem** [comment]
@mattpannella Well, now that you mention it, the OpenFPGA inventory might actually have something in the works that we could leverage. The replacement core feature that's pending.

We could do something similar called "alternative setups" or something. Then the tool can read that info and ask the user what they want. The repos for the alternative setups would have to be done in a way where all the files that weren't changed got linked to, so the entire core setup could be downloaded (I'm pretty sure this is possible).

I'd definitely be up for bringing in the others to brainstorm about this with. I just don't have the connections with them that you do. #newguyproblems lol. We might want to bring in dyreschlock too since his stuff is the first use case.

**Comment by hallem** [comment]
There's a preview of both the menu redesign and the pocket extras work here:
https://github.com/mattpannella/pupdate/compare/main...hallem:pupdate:pocket-extras?expand=1
